# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Apprenda Documentation

title: Apprenda Audit Event SIEM Exports
email: jchoy@apprenda.com
description: >- # this means to ignore newlines until "baseurl:"
  Apprenda Cloud Platform Extension samples to integrate 
  with syslog-transport SIEM log collectors, including ArcSight Common Event Format
  representation of log events  
baseurl: "/AuditEvents-SIEM" # the subpath of your site, e.g. /blog
url: "http://apprenda.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  apprenda
template_features:
  breadcrumb: no
  sidebar: no
site:
  show_downloads: "true"
sass:
  style: compressed
# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
